sudo: false

language: ruby

cache: bundler

bundler_args: --without development

rvm:
  - 2.3.1
  - 2.3.0
  - 2.2
  - 2.1
  - 2.0.0
  - ruby-head
  - jruby-head
  - rbx-2

matrix:
  include:
    - rvm: 2.3.1
      script:
        - bundle exec danger
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-2
